name: .NET Framework

on:
  push:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
  workflow_dispatch:

jobs:
  run-unit-tests:
    strategy:
      matrix:
        configuration: [Debug, Release]
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      TestProjectPath: Source\Bluechirp.Tests\Bluechirp.Tests.csproj
      TestExecutablePath: Source\Bluechirp.Tests\bin\${{ matrix.targetplatform }}\${{ matrix.configuration }}\Bluechirp.Tests.build.appxrecipe

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Setup Build
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Build Tests
      run: >
        msbuild ${{ env.TestProjectPath }} -t:restore /p:Platform=${{ matrix.targetplatform }} /p:Configuration=${{ matrix.configuration }};
        msbuild ${{ env.TestProjectPath }} -t:build /p:Platform=${{ matrix.targetplatform }} /p:Configuration=${{ matrix.configuration }}
        
    # Execute all unit tests in the solution
    - name: Execute Tests
      run: >
        $vs_path = vswhere -latest -products * -requires Microsoft.VisualStudio.Workload.ManagedDesktop -requiresAny -property installationPath;
        $vstest_path = join-path $vs_path 'Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe';
        & $vstest_path /Platform:${{ matrix.targetplatform }} /framework:frameworkuap10 ${{ env.TestExecutablePath }}

